import { Densities } from "@/types/density";

export const CALENDAR_DENSITY_CONFIG = {
  [Densities.Small]: {
    toolbarButtonPadding: "px-2 py-1",
    toolbarButtonText: "text-xs",
    toolbarTitleText: "text-sm font-semibold",
    eventPillText: "text-[10px]",
    eventPillPadding: "px-1 py-px",
    monthCellMinHeight: "min-h-[3.5rem]",
    dayBadgeSize: "size-5 text-[10px]",
    timeGutterWidth: "w-14",
    dayHeaderBadge: "size-6 text-base",
    agendaDateWidth: "w-28",
    agendaRowPadding: "px-2 py-1.5",
    agendaDotSize: "size-2",
    timeEventPadding: "px-1 py-px text-[10px]",
    hourHeight: 48,
  },
  [Densities.Medium]: {
    toolbarButtonPadding: "px-3 py-1.5",
    toolbarButtonText: "text-sm",
    toolbarTitleText: "text-base font-semibold",
    eventPillText: "text-xs",
    eventPillPadding: "px-1.5 py-0.5",
    monthCellMinHeight: "min-h-[4.5rem]",
    dayBadgeSize: "size-6 text-xs",
    timeGutterWidth: "w-16",
    dayHeaderBadge: "size-8 text-lg",
    agendaDateWidth: "w-32",
    agendaRowPadding: "px-3 py-2",
    agendaDotSize: "w-2.5 h-2.5",
    timeEventPadding: "px-1.5 py-0.5 text-xs",
    hourHeight: 60,
  },
  [Densities.Large]: {
    toolbarButtonPadding: "px-4 py-2",
    toolbarButtonText: "text-base",
    toolbarTitleText: "text-lg font-semibold",
    eventPillText: "text-sm",
    eventPillPadding: "px-2 py-1",
    monthCellMinHeight: "min-h-[5.5rem]",
    dayBadgeSize: "size-7 text-sm",
    timeGutterWidth: "w-20",
    dayHeaderBadge: "size-10 text-xl",
    agendaDateWidth: "w-36",
    agendaRowPadding: "px-4 py-3",
    agendaDotSize: "size-3",
    timeEventPadding: "px-2 py-1 text-sm",
    hourHeight: 72,
  },
} as const;
